Tweaked symlinks so unpacked paths point to correct locations
anatol/booster pull request #179
Opened 2022-09-03 18:04 UTC by thomasfsteeples

Currently, in the `generator` test suite, I have several tests failing, including ` TestExtraFiles`, ` TestEnableVirtualConsole`, `TestEnableVirtualConsoleWithoutLocaleConf`. This seems to be because the symlinks are currently set up to point to the root directory. Whilst this is fine when used in practice as an initramfs, it means that when unpacked, it points to the root directory of the host machine (which is not the intended effect). Removing the leading slash makes the test suite pass, and the resulting image remains bootable.

2022-09-07 15:15 UTC, anatol requested changes

2022-09-07 15:15 UTC, anatol commented on generator/generator.go
>  	symlinks := []struct{ src, target string }{
So you are basically using relative symlinks. It is better to change the commit description "Tweaked symlinks" -> "Use relative symlinks".

2022-09-07 15:15 UTC, anatol commented on generator/generator.go
> -		{"/usr/local/lib", "/usr/lib"},
the target needs to be "../usr/lib"

2022-09-07 15:15 UTC, anatol commented on generator/generator.go
> -		{"/usr/sbin", "/usr/bin"},
target needs to be "../usr/bin"

2022-09-07 15:15 UTC, anatol commented on generator/generator.go
> -		{"/usr/local/bin", "/usr/bin"},
ditto

2022-09-07 15:15 UTC, anatol commented on generator/generator.go
> -		{"/usr/local/sbin", "/usr/bin"},
ditto.

here and any other place where symlinks cross directory hierarchy

2022-10-04 17:04 UTC, anatol commented
@thomasfsteeples I would like to take care of your changes and move forward. Are you OK with it?

2022-10-04 17:40 UTC, thomasfsteeples commented
@anatol Absolutely fine with me; sorry I never got round to it!

2022-10-11 02:24 UTC, anatol commented
Pushed this PR to `wip` branch as 209f8cce95ab08c9c5f840aaff0a7ab61f1ac89c

2022-10-11 02:24 UTC, closed without merging